name: TODO issue generator

on:
  push:
    branches: [ "*" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: pip install -r .github/workflows/requirements.txt
    - name: Real Pull
      run: git fetch --unshallow
    - name: make issue
      run: python3 .github/workflows/todo.py --token ${{ secrets.GITHUB_TOKEN }}
